%eventAlignedTraces
%We would like to acknowledge the use of OpenAI’s ChatGPT (versions 4o, 5, 
% 5.1, 5.2) as an auxiliary tool for code optimization.
%% Import data
streamsPath = "C:\Users\walki\Box\Filtering Paper\resubmission\Figures\Photometry Figure\Extra_Stuff\EvanStorage\streams.csv";
trialsPath = "C:\Users\walki\Box\Filtering Paper\resubmission\Figures\Photometry Figure\Extra_Stuff\EvanStorage\trials.csv";
sessionsPath = "C:\Users\walki\Box\Filtering Paper\resubmission\Figures\Photometry Figure\Extra_Stuff\EvanStorage\sessions.csv";
signalsPath = "C:\Users\walki\Box\Filtering Paper\resubmission\Figures\Photometry Figure\Extra_Stuff\EvanStorage\signals2.h5";
streams = readtable(streamsPath, "TextType", "string");
trials = readtable(trialsPath, "TextType", "string");
sessions = readtable(sessionsPath, "TextType", "string");

%% Exclude Nrxn1a
streams = streams(streams.nrxn ==0,:);
trials = trials(trials.nrxn == 0,:);
sessions = sessions(sessions.nrxn ==0,:);
%

%% Exclude mistargeted animals
%DATA QUALITY/CLEANING EXCLUSIONS + REASONS:
% Exclude:
% o	a2ac213 right - Reason: no right fiber
% o	d1c176 left - Reason: mistargeted (see histology)
% o	d1c209 left - Reason: mistargeted (see histology)
% o	d1c217 left - Reason: mistargeted (see histology)
exclusions = table( ...
    ["a2ac213"; "d1c176"; "d1c209"; "d1c217"], ...
    ["R";       "L";       "L";       "L"], ...
    ["no right fiber";
     "mistargeted (histology)";
     "mistargeted (histology)";
     "mistargeted (histology)"], ...
    'VariableNames', {'animal_id','side','reason'});
streams.include = true(height(streams),1);
streams.exclude_reason = strings(height(streams),1);

for k = 1:height(exclusions)
    mask = (streams.animal_id == exclusions.animal_id(k)) & ...
           (streams.side      == exclusions.side(k));
    streams.include(mask) = false;
    streams.exclude_reason(mask) = exclusions.reason(k);
end

streams = streams(streams.include == 1,:);
% no need to exclude trials or sessions because these are all unilateral
% exclusions. IF THIS CHANGES, WE NEED TO RECODE. 

%% Define colors for plotting
a2aColor = [255,51,153];
d1Color = [51,51,153];

hitColor = [0.20 0.65 0.35];
missColor = [0.20 0.70 0.75];
FAColor = [0.80 0.25 0.30];
CRColor = [0.35 0.30 0.70];

goColor = [0.25 0.60 0.40];
nogoColor = [0.75 0.30 0.30];

highToneColor = [0.25 0.70 0.75];
lowToneColor  = [0.90 0.65 0.20];


%% Trial-start Z-scored traces D1 overlay A2A per reviewer comment
figure; hold on
[hTStartD1,metaTStartD1] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","trial_start", "which","normalized", ...
    "Color",d1Color, "FillAlpha",0.12, "weight_by","animal");
[hTStartA2A,metaTStartA2A] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","trial_start", "which","normalized", ...
    "Color",a2aColor, "FillAlpha",0.12, "weight_by","animal");
text(0.98, 0.98, 'D1-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', d1Color./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'A2A-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', a2aColor./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');



%% D1/A2A Overlay, debleached vs. debleached+Zscore, Trial Start, Tone Start, Outcome Start
figure;
tiledlayout(2,3);
nexttile; hold on
[hTStartD1,metaTStartD1] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","trial_start", "which","debleached", ...
    "Color",d1Color, "FillAlpha",0.12, "weight_by","animal");
[hTStartA2A,metaTStartA2A] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","trial_start", "which","debleached", ...
    "Color",a2aColor, "FillAlpha",0.12, "weight_by","animal");
title("Trial Start")
ylabel("ΔF/F");
text(0.98, 0.98, 'D1-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', d1Color./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'A2A-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', a2aColor./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hToStartD1,metaToStartD1] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", ...
    "Color",d1Color, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2A,metaToStartA2A] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", ...
    "Color",a2aColor, "FillAlpha",0.12, "weight_by","animal");
title("Tone Start")
ylabel("ΔF/F");
text(0.98, 0.98, 'D1-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', d1Color./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'A2A-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', a2aColor./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hOStartD1,metaOStartD1] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","outcome", "which","debleached", ...
    "Color",d1Color, "FillAlpha",0.12, "weight_by","animal");
[hOStartA2A,metaOStartA2A] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","outcome", "which","debleached", ...
    "Color",a2aColor, "FillAlpha",0.12, "weight_by","animal");
title("Outcome")
ylabel("ΔF/F");
text(0.98, 0.98, 'D1-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', d1Color./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'A2A-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', a2aColor./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');


nexttile; hold on
[hTStartD1Z,metaTStartD1Z] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","trial_start", "which","normalized", ...
    "Color",d1Color, "FillAlpha",0.12, "weight_by","animal");
[hTStartA2AZ,metaTStartA2AZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","trial_start", "which","normalized", ...
    "Color",a2aColor, "FillAlpha",0.12, "weight_by","animal");
title("Trial Start")
ylabel("Z-scored ΔF/F");
text(0.98, 0.98, 'D1-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', d1Color./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'A2A-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', a2aColor./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hToStartD1Z,metaToStartD1Z] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","normalized", ...
    "Color",d1Color, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2AZ,metaToStartA2AZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","normalized", ...
    "Color",a2aColor, "FillAlpha",0.12, "weight_by","animal");
title("Tone Start")
ylabel("Z-scored ΔF/F");
text(0.98, 0.98, 'D1-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', d1Color./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'A2A-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', a2aColor./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hOStartD1Z,metaOStartD1Z] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","outcome", "which","normalized", ...
    "Color",d1Color, "FillAlpha",0.12, "weight_by","animal");
[hOStartA2AZ,metaOStartA2AZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","outcome", "which","normalized", ...
    "Color",a2aColor, "FillAlpha",0.12, "weight_by","animal");
title("Outcome")
ylabel("Z-scored ΔF/F");
text(0.98, 0.98, 'D1-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', d1Color./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'A2A-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', a2aColor./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');



%% D1 // A2A activity at TRIAL Start Separated by Same-Trial Outcome - DB, DBZ

figure;
tiledlayout(2,2);
nexttile; hold on
[hTStartD1hit,metaTStartD1hit] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","trial_start", "which","debleached", "outcome","hit",...
    "Color",hitColor, "FillAlpha",0.12, "weight_by","animal");
%[hTStartD1miss,metaTStartD1miss] = plotPhotometryQuery(streams, trials, signalsPath, ...
%      "cell_type","d1", "align","trial_start", "which","debleached", "outcome","miss",...
%      "Color",missColor, "FillAlpha",0.12, "weight_by","animal");
[hTStartD1FA,metaTStartD1FA] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","trial_start", "which","debleached", "outcome","fa",...
    "Color",FAColor, "FillAlpha",0.12, "weight_by","animal");
[hTStartD1CR,metaTStartD1CR] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","trial_start", "which","debleached", "outcome","cr",...
    "Color",CRColor, "FillAlpha",0.12, "weight_by","animal");


title("D1 SPN - Trial Start")
ylabel("ΔF/F");
text(0.98, 0.98, 'Hit', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', hitColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Correct Rejection', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', CRColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
% text(0.98, 0.82, 'Miss', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','right', ...
%     'VerticalAlignment','top', ...
%     'Color', missColor, ...
%     'FontSize', 10, ...
%     'FontWeight','bold');
text(0.98, 0.74, 'False Alarm', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', FAColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hTStartA2Ahit,metaTStartA2Ahit] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","trial_start", "which","debleached", "outcome","hit",...
    "Color",hitColor, "FillAlpha",0.12, "weight_by","animal");
%[hTStartA2Amiss,metaTStartA2Amiss] = plotPhotometryQuery(streams, trials, signalsPath, ...
%      "cell_type","a2a", "align","trial_start", "which","debleached", "outcome","miss",...
%      "Color",missColor, "FillAlpha",0.12, "weight_by","animal");
[hTStartA2AFA,metaTStartA2AFA] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","trial_start", "which","debleached", "outcome","fa",...
    "Color",FAColor, "FillAlpha",0.12, "weight_by","animal");
[hTStartA2ACR,metaTStartA2ACR] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","trial_start", "which","debleached", "outcome","cr",...
    "Color",CRColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Trial Start")
ylabel("ΔF/F");
text(0.98, 0.98, 'Hit', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', hitColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Correct Rejection', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', CRColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
% text(0.98, 0.82, 'Miss', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','right', ...
%     'VerticalAlignment','top', ...
%     'Color', missColor, ...
%     'FontSize', 10, ...
%     'FontWeight','bold');
text(0.98, 0.74, 'False Alarm', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', FAColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hTStartD1hitZ,metaTStartD1hitZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","trial_start", "which","normalized", "outcome","hit",...
    "Color",hitColor, "FillAlpha",0.12, "weight_by","animal");
%[hTStartD1missZ,metaTStartD1missZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
%      "cell_type","d1", "align","trial_start", "which","normalized", "outcome","miss",...
%      "Color",missColor, "FillAlpha",0.12, "weight_by","animal");
[hTStartD1FAZ,metaTStartD1FAZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","trial_start", "which","normalized", "outcome","fa",...
    "Color",FAColor, "FillAlpha",0.12, "weight_by","animal");
[hTStartD1CRZ,metaTStartD1CRZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","trial_start", "which","normalized", "outcome","cr",...
    "Color",CRColor, "FillAlpha",0.12, "weight_by","animal");


title("D1 SPN - Trial Start")
ylabel("Z-scored ΔF/F");
text(0.98, 0.98, 'Hit', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', hitColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Correct Rejection', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', CRColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
% text(0.98, 0.82, 'Miss', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','right', ...
%     'VerticalAlignment','top', ...
%     'Color', missColor, ...
%     'FontSize', 10, ...
%     'FontWeight','bold');
text(0.98, 0.74, 'False Alarm', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', FAColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hTStartA2AhitZ,metaTStartA2AhitZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","trial_start", "which","normalized", "outcome","hit",...
    "Color",hitColor, "FillAlpha",0.12, "weight_by","animal");
%[hTStartA2AmissZ,metaTStartA2AmissZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
%      "cell_type","a2a", "align","trial_start", "which","normalized", "outcome","miss",...
%      "Color",missColor, "FillAlpha",0.12, "weight_by","animal");
[hTStartA2AFAZ,metaTStartA2AFAZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","trial_start", "which","normalized", "outcome","fa",...
    "Color",FAColor, "FillAlpha",0.12, "weight_by","animal");
[hTStartA2ACRZ,metaTStartA2ACRZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","trial_start", "which","normalized", "outcome","cr",...
    "Color",CRColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Trial Start")
ylabel("Z-scored ΔF/F");
text(0.98, 0.98, 'Hit', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', hitColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Correct Rejection', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', CRColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
% text(0.98, 0.82, 'Miss', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','right', ...
%     'VerticalAlignment','top', ...
%     'Color', missColor, ...
%     'FontSize', 10, ...
%     'FontWeight','bold');
text(0.98, 0.74, 'False Alarm', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', FAColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

%% D1 // A2A activity at TONE Start Separated by Same-Trial Outcome - DB, DBZ

figure;
tiledlayout(2,2);
nexttile; hold on
[hToStartD1hit,metaToStartD1hit] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "outcome","hit",...
    "Color",hitColor, "FillAlpha",0.12, "weight_by","animal");
%[hToStartD1miss,metaToStartD1miss] = plotPhotometryQuery(streams, trials, signalsPath, ...
%      "cell_type","d1", "align","tone_start", "which","debleached", "outcome","miss",...
%      "Color",missColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1FA,metaToStartD1FA] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "outcome","fa",...
    "Color",FAColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1CR,metaToStartD1CR] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "outcome","cr",...
    "Color",CRColor, "FillAlpha",0.12, "weight_by","animal");


title("D1 SPN - Tone Start")
ylabel("ΔF/F");
text(0.98, 0.98, 'Hit', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', hitColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Correct Rejection', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', CRColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
% text(0.98, 0.82, 'Miss', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','right', ...
%     'VerticalAlignment','top', ...
%     'Color', missColor, ...
%     'FontSize', 10, ...
%     'FontWeight','bold');
text(0.98, 0.74, 'False Alarm', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', FAColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

% ---------- D1: build AUC table from your existing meta vars ----------
t = -2:0.025:2;            % make sure meta.t = tc in plotPhotometryQuery
t0 = 0.15;  tEnd = 1.15;
tMid = (t0 + tEnd)/2;              % or pick a biologically motivated split

A_D1_hit = auc2bins_stream(t, metaToStartD1hit.stream_traces, t0, tMid, tEnd);
A_D1_fa  = auc2bins_stream(t, metaToStartD1FA.stream_traces,  t0, tMid, tEnd);
A_D1_cr  = auc2bins_stream(t, metaToStartD1CR.stream_traces,  t0, tMid, tEnd);

% helper to make long-format rows (stream-level)
mkBlock = @(meta, A, outLabel) table( ...
    repmat(categorical(string(outLabel), ["hit","fa","cr"]), size(A,1)*2, 1), ...
    repmat(string(meta.animal_id),   2, 1), ...
    repmat(string(meta.session_uid), 2, 1), ...
    repmat(string(meta.stream_uid),  2, 1), ...
    [repmat(categorical("early",["early","late"]), size(A,1),1); repmat(categorical("late",["early","late"]), size(A,1),1)], ...
    [A(:,1); A(:,2)], ...
    'VariableNames', {'outcome','animal_id','session_uid','stream_uid','timebin','auc'} );

T_D1 = [ ...
    mkBlock(metaToStartD1hit, A_D1_hit, "hit"); ...
    mkBlock(metaToStartD1FA,  A_D1_fa,  "fa");  ...
    mkBlock(metaToStartD1CR,  A_D1_cr,  "cr")   ...
];

% ---------- LME per time bin (cleanest, matches your kernel AUC logic) ----------
T_D1_early = T_D1(T_D1.timebin=="early",:);
lme_D1_E = fitlme(T_D1_early, 'auc ~ outcome + (1|animal_id)');
anova_D1_E = anova(lme_D1_E, 'DFMethod','Satterthwaite')

C_cr_hit = [0 1 0];
[p_cr_hit, F_cr_hit] = coefTest(lme_D1_E, C_cr_hit);

C_fa_hit = [0 0 1];
[p_fa_hit, F_fa_hit] = coefTest(lme_D1_E, C_fa_hit);

C_fa_cr = [0 -1 1];
[p_fa_cr, F_fa_cr] = coefTest(lme_D1_E, C_fa_cr);

T_D1_late = T_D1(T_D1.timebin=="late",:);
lme_D1_L = fitlme(T_D1_late, 'auc ~ outcome + (1|animal_id)');
anova_D1_L = anova(lme_D1_L, 'DFMethod','Satterthwaite')

t = -2:0.025:2;

baseIx = t>=-0.5 & t<=0;
peakIx = t>=0    & t<=0.4;

% robust-ish peak: mean of top k samples
k = 5;

peakMetric = @(M) ...
    mean(maxk(M(:,peakIx), k, 2), 2) - mean(M(:,baseIx), 2);

% D1 metrics per outcome (one value per stream)
yD1_hit = peakMetric(metaToStartD1hit.stream_traces);
yD1_fa  = peakMetric(metaToStartD1FA.stream_traces);
yD1_cr  = peakMetric(metaToStartD1CR.stream_traces);

mkPeakBlock = @(meta, y, outLabel) table( ...
    repmat(categorical(string(outLabel), ["hit","fa","cr"]), numel(y), 1), ...
    string(meta.animal_id), string(meta.session_uid), string(meta.stream_uid), ...
    y, 'VariableNames', {'outcome','animal_id','session_uid','stream_uid','peak'} );

Tpk_D1 = [ ...
    mkPeakBlock(metaToStartD1hit, yD1_hit, "hit"); ...
    mkPeakBlock(metaToStartD1FA,  yD1_fa,  "fa");  ...
    mkPeakBlock(metaToStartD1CR,  yD1_cr,  "cr")   ...
];

% LME (Hit baseline if your categorical is ordered that way)
Tpk_D1.outcome = categorical(Tpk_D1.outcome, ["hit","cr","fa"]); % <- hit baseline
lme_pk_D1 = fitlme(Tpk_D1, 'peak ~ outcome + (1|animal_id)');
anova(lme_pk_D1,'DFMethod','Satterthwaite')


% CR vs HIT
[p_cr_hit_d1,~] = coefTest(lme_pk_D1, [0 1 0]);

% FA vs HIT
[p_fa_hit_d1,~] = coefTest(lme_pk_D1, [0 0 1]);

% FA vs CR
[p_fa_cr_d1,~]  = coefTest(lme_pk_D1, [0 -1 1]);

p_raw_d1 = [p_cr_hit_d1, p_fa_hit_d1, p_fa_cr_d1];
q_d1 = mafdr(p_raw_d1, 'BHFDR', true);

% optional post-hoc (only if omnibus is significant)
% mc_D1_E = multcompare(lme_D1_E, 'outcome', 'ComparisonType','tukey');
% mc_D1_L = multcompare(lme_D1_L, 'outcome', 'ComparisonType','tukey');

nexttile; hold on
[hToStartA2Ahit,metaToStartA2Ahit] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "outcome","hit",...
    "Color",hitColor, "FillAlpha",0.12, "weight_by","animal");
%[hToStartA2Amiss,metaToStartA2Amiss] = plotPhotometryQuery(streams, trials, signalsPath, ...
%      "cell_type","a2a", "align","tone_start", "which","debleached", "outcome","miss",...
%      "Color",missColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2AFA,metaToStartA2AFA] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "outcome","fa",...
    "Color",FAColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2ACR,metaToStartA2ACR] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "outcome","cr",...
    "Color",CRColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Tone Start")
ylabel("ΔF/F");
text(0.98, 0.98, 'Hit', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', hitColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Correct Rejection', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', CRColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
% text(0.98, 0.82, 'Miss', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','right', ...
%     'VerticalAlignment','top', ...
%     'Color', missColor, ...
%     'FontSize', 10, ...
%     'FontWeight','bold');
text(0.98, 0.74, 'False Alarm', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', FAColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

% ---------- A2A: build AUC table from your existing meta vars ----------
t = -2:0.025:2;            % make sure meta.t = tc in plotPhotometryQuery
t0 = 0.15;  tEnd = 1.15;
tMid = (t0 + tEnd)/2;              % or pick a biologically motivated split

A_A2A_hit = auc2bins_stream(t, metaToStartA2Ahit.stream_traces, t0, tMid, tEnd);
A_A2A_fa  = auc2bins_stream(t, metaToStartA2AFA.stream_traces,  t0, tMid, tEnd);
A_A2A_cr  = auc2bins_stream(t, metaToStartA2ACR.stream_traces,  t0, tMid, tEnd);

% helper to make long-format rows (stream-level)
mkBlock = @(meta, A, outLabel) table( ...
    repmat(categorical(string(outLabel), ["hit","fa","cr"]), size(A,1)*2, 1), ...
    repmat(string(meta.animal_id),   2, 1), ...
    repmat(string(meta.session_uid), 2, 1), ...
    repmat(string(meta.stream_uid),  2, 1), ...
    [repmat(categorical("early",["early","late"]), size(A,1),1); repmat(categorical("late",["early","late"]), size(A,1),1)], ...
    [A(:,1); A(:,2)], ...
    'VariableNames', {'outcome','animal_id','session_uid','stream_uid','timebin','auc'} );

T_A2A = [ ...
    mkBlock(metaToStartA2Ahit, A_A2A_hit, "hit"); ...
    mkBlock(metaToStartA2AFA,  A_A2A_fa,  "fa");  ...
    mkBlock(metaToStartA2ACR,  A_A2A_cr,  "cr")   ...
];

% ---------- LME per time bin (cleanest, matches your kernel AUC logic) ----------
T_A2A_early = T_A2A(T_A2A.timebin=="early",:);
lme_A2A_E = fitlme(T_A2A_early, 'auc ~ outcome + (1|animal_id)');
anova_A2A_E = anova(lme_A2A_E, 'DFMethod','Satterthwaite')

C_cr_hit = [0 1 0];
[p_cr_hit, F_cr_hit] = coefTest(lme_A2A_E, C_cr_hit);

C_fa_hit = [0 0 1];
[p_fa_hit, F_fa_hit] = coefTest(lme_A2A_E, C_fa_hit);

C_fa_cr = [0 -1 1];
[p_fa_cr, F_fa_cr] = coefTest(lme_A2A_E, C_fa_cr);

T_A2A_late = T_A2A(T_A2A.timebin=="late",:);
lme_A2A_L = fitlme(T_A2A_late, 'auc ~ outcome + (1|animal_id)');
anova_A2A_L = anova(lme_A2A_L, 'DFMethod','Satterthwaite')

t = -2:0.025:2;

baseIx = t>=-0.5 & t<=0;
peakIx = t>=0    & t<=0.4;

% robust-ish peak: mean of top k samples
k = 5;

peakMetric = @(M) ...
    mean(maxk(M(:,peakIx), k, 2), 2) - mean(M(:,baseIx), 2);

% A2A metrics per outcome (one value per stream)
yA2A_hit = peakMetric(metaToStartA2Ahit.stream_traces);
yA2A_fa  = peakMetric(metaToStartA2AFA.stream_traces);
yA2A_cr  = peakMetric(metaToStartA2ACR.stream_traces);

mkPeakBlock = @(meta, y, outLabel) table( ...
    repmat(categorical(string(outLabel), ["hit","fa","cr"]), numel(y), 1), ...
    string(meta.animal_id), string(meta.session_uid), string(meta.stream_uid), ...
    y, 'VariableNames', {'outcome','animal_id','session_uid','stream_uid','peak'} );

Tpk_A2A = [ ...
    mkPeakBlock(metaToStartA2Ahit, yA2A_hit, "hit"); ...
    mkPeakBlock(metaToStartA2AFA,  yA2A_fa,  "fa");  ...
    mkPeakBlock(metaToStartA2ACR,  yA2A_cr,  "cr")   ...
];

% LME (Hit baseline if your categorical is ordered that way)
Tpk_A2A.outcome = categorical(Tpk_A2A.outcome, ["hit","cr","fa"]); % <- hit baseline
lme_pk_A2A = fitlme(Tpk_A2A, 'peak ~ outcome + (1|animal_id)');
anova(lme_pk_A2A,'DFMethod','Satterthwaite')

% CR vs HIT
[p_cr_hit_a2a,~] = coefTest(lme_pk_A2A, [0 1 0]);

% FA vs HIT
[p_fa_hit_a2a,~] = coefTest(lme_pk_A2A, [0 0 1]);

% FA vs CR
[p_fa_cr_a2a,~]  = coefTest(lme_pk_A2A, [0 -1 1]);

p_raw_a2a = [p_cr_hit_a2a, p_fa_hit_a2a, p_fa_cr_a2a];
q_a2a = mafdr(p_raw_a2a, 'BHFDR', true);

nexttile; hold on
[hToStartD1hitZ,metaToStartD1hitZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","normalized", "outcome","hit",...
    "Color",hitColor, "FillAlpha",0.12, "weight_by","animal");
%[hToStartD1missZ,metaToStartD1missZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
%      "cell_type","d1", "align","tone_start", "which","normalized", "outcome","miss",...
%      "Color",missColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1FAZ,metaToStartD1FAZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","normalized", "outcome","fa",...
    "Color",FAColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1CRZ,metaToStartD1CRZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","normalized", "outcome","cr",...
    "Color",CRColor, "FillAlpha",0.12, "weight_by","animal");


title("D1 SPN - Tone Start")
ylabel("Z-scored ΔF/F");
text(0.98, 0.98, 'Hit', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', hitColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Correct Rejection', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', CRColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
% text(0.98, 0.82, 'Miss', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','right', ...
%     'VerticalAlignment','top', ...
%     'Color', missColor, ...
%     'FontSize', 10, ...
%     'FontWeight','bold');
text(0.98, 0.74, 'False Alarm', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', FAColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hToStartA2AhitZ,metaToStartA2AhitZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","normalized", "outcome","hit",...
    "Color",hitColor, "FillAlpha",0.12, "weight_by","animal");
%[hToStartA2AmissZ,metaToStartA2AmissZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
%      "cell_type","a2a", "align","tone_start", "which","normalized", "outcome","miss",...
%      "Color",missColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2AFAZ,metaToStartA2AFAZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","normalized", "outcome","fa",...
    "Color",FAColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2ACRZ,metaToStartA2ACRZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","normalized", "outcome","cr",...
    "Color",CRColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Tone Start")
ylabel("Z-scored ΔF/F");
text(0.98, 0.98, 'Hit', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', hitColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Correct Rejection', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', CRColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
% text(0.98, 0.82, 'Miss', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','right', ...
%     'VerticalAlignment','top', ...
%     'Color', missColor, ...
%     'FontSize', 10, ...
%     'FontWeight','bold');
text(0.98, 0.74, 'False Alarm', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', FAColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');


% plot_peak_triplet_by_animal(Tpk_A2A, 'A2A peak comparison');
% plot_peak_triplet_by_animal(Tpk_D1,  'D1 peak comparison');

%% ...D1 peak comparisons
T = Tpk_D1;

% standardize outcome labels
T.outcome = categorical(lower(string(T.outcome)));

% keep only hit/fa/cr
keep = ismember(T.outcome, ["hit","fa","cr"]);
T = T(keep,:);

% collapse streams within session
G1 = findgroups(T.animal_id, T.session_uid, T.outcome);
peak_sess = splitapply(@mean, T.peak, G1);

animal_sess = splitapply(@(x)x(1), T.animal_id, G1);
outcome_sess = splitapply(@(x)x(1), T.outcome, G1);

Tsess = table(animal_sess, outcome_sess, peak_sess, ...
    'VariableNames', {'animal_id','outcome','peak'});

% collapse sessions within animal
G2 = findgroups(Tsess.animal_id, Tsess.outcome);
peak_animal = splitapply(@mean, Tsess.peak, G2);

animal = splitapply(@(x)x(1), Tsess.animal_id, G2);
outcome = splitapply(@(x)x(1), Tsess.outcome, G2);

Tanimal = table(animal, outcome, peak_animal, ...
    'VariableNames', {'animal_id','outcome','peak'});

animals = unique(Tanimal.animal_id);
nA = numel(animals);

Y = nan(nA,3); % columns: [Hit FA CR]

for i = 1:nA
    a = animals(i);
    
    for j = 1:3
        cond = ["hit","fa","cr"];
        idx = Tanimal.animal_id == a & Tanimal.outcome == cond(j);
        if any(idx)
            Y(i,j) = Tanimal.peak(idx);
        end
    end
end
% --- compute deltas ---
delta_Hit_CR = Y(:,1) - Y(:,3);
delta_FA_CR  = Y(:,2) - Y(:,3);
delta_Hit_FA = Y(:,1) - Y(:,2);

D = {delta_Hit_CR, delta_FA_CR, delta_Hit_FA};
labels = {'Hit - CR','FA - CR','Hit - FA'};

figure('Color','w','Position',[100 100 900 350]);
% Match to delta order:
% 1) Hit - CR
% 2) FA - CR
% 3) Hit - FA

q_for_plot = [
    q_d1(1) ;  % CR vs Hit  -> Hit - CR
    q_d1(3) ;  % FA vs CR   -> FA - CR
    q_d1(2)    % FA vs Hit  -> Hit - FA
];

for i = 1:3
    subplot(1,3,i); hold on;
    
    y = D{i};
    
    % scatter individual animals (slight horizontal jitter)
    xj = 1 + 0.02*randn(size(y));
    scatter(xj, y, 40, ...
        'MarkerFaceColor',[0.5 0.5 0.5], ...
        'MarkerEdgeColor','none', ...
        'MarkerFaceAlpha',0.8);
    
    % mean ± SEM
    mu = mean(y,'omitnan');
    sem = std(y,'omitnan') / sqrt(sum(~isnan(y)));
    
    errorbar(1, mu, sem, 'k', 'LineWidth', 2, 'CapSize', 12);
    scatter(1, mu, 100, 'k', 'filled');
    
    % zero reference line
    yline(0,'--','Color',[0.6 0.6 0.6],'LineWidth',1);
    
    xlim([0.85 1.15]);
    set(gca,'XTick',[]);
    title(labels{i});
    box off;
    set(gca,'LineWidth',1.2,'FontSize',12);
end
for i = 1:3
    subplot(1,3,i);
    ylim_current = ylim;
    
    text(1, ...
         ylim_current(2) - 0.05*range(ylim_current), ...
         sprintf('q = %.3g', q_for_plot(i)), ...
         'HorizontalAlignment','center', ...
         'FontSize',11, ...
         'FontWeight','normal');
end

sgtitle('D1 Peak Differences (within-animal deltas)');
%% ...A2A peak comparisons
T = Tpk_A2A;

% standardize outcome labels
T.outcome = categorical(lower(string(T.outcome)));

% keep only hit/fa/cr
keep = ismember(T.outcome, ["hit","fa","cr"]);
T = T(keep,:);

% collapse streams within session
G1 = findgroups(T.animal_id, T.session_uid, T.outcome);
peak_sess = splitapply(@mean, T.peak, G1);

animal_sess = splitapply(@(x)x(1), T.animal_id, G1);
outcome_sess = splitapply(@(x)x(1), T.outcome, G1);

Tsess = table(animal_sess, outcome_sess, peak_sess, ...
    'VariableNames', {'animal_id','outcome','peak'});

% collapse sessions within animal
G2 = findgroups(Tsess.animal_id, Tsess.outcome);
peak_animal = splitapply(@mean, Tsess.peak, G2);

animal = splitapply(@(x)x(1), Tsess.animal_id, G2);
outcome = splitapply(@(x)x(1), Tsess.outcome, G2);

Tanimal = table(animal, outcome, peak_animal, ...
    'VariableNames', {'animal_id','outcome','peak'});

animals = unique(Tanimal.animal_id);
nA = numel(animals);

Y = nan(nA,3); % columns: [Hit FA CR]

for i = 1:nA
    a = animals(i);
    
    for j = 1:3
        cond = ["hit","fa","cr"];
        idx = Tanimal.animal_id == a & Tanimal.outcome == cond(j);
        if any(idx)
            Y(i,j) = Tanimal.peak(idx);
        end
    end
end
% --- compute deltas ---
delta_Hit_CR = Y(:,1) - Y(:,3);
delta_FA_CR  = Y(:,2) - Y(:,3);
delta_Hit_FA = Y(:,1) - Y(:,2);

D = {delta_Hit_CR, delta_FA_CR, delta_Hit_FA};
labels = {'Hit - CR','FA - CR','Hit - FA'};

figure('Color','w','Position',[100 100 900 350]);
% Match to delta order:
% 1) Hit - CR
% 2) FA - CR
% 3) Hit - FA

q_for_plot = [
    q_a2a(1) ;  % CR vs Hit  -> Hit - CR
    q_a2a(3) ;  % FA vs CR   -> FA - CR
    q_a2a(2)    % FA vs Hit  -> Hit - FA
];


for i = 1:3
    subplot(1,3,i); hold on;
    
    y = D{i};
    
    % scatter individual animals (slight horizontal jitter)
    xj = 1 + 0.02*randn(size(y));
    scatter(xj, y, 40, ...
        'MarkerFaceColor',[0.5 0.5 0.5], ...
        'MarkerEdgeColor','none', ...
        'MarkerFaceAlpha',0.8);
    
    % mean ± SEM
    mu = mean(y,'omitnan');
    sem = std(y,'omitnan') / sqrt(sum(~isnan(y)));
    
    errorbar(1, mu, sem, 'k', 'LineWidth', 2, 'CapSize', 12);
    scatter(1, mu, 100, 'k', 'filled');
    
    % zero reference line
    yline(0,'--','Color',[0.6 0.6 0.6],'LineWidth',1);
    xlim([0.85 1.15]);
    set(gca,'XTick',[]);
    title(labels{i});
    box off;
    set(gca,'LineWidth',1.2,'FontSize',12);
end
for i = 1:3
    subplot(1,3,i);
    ylim_current = ylim;
    
    text(1, ...
         ylim_current(2) - 0.05*range(ylim_current), ...
         sprintf('q = %.3f', q_for_plot(i)), ...
         'HorizontalAlignment','center', ...
         'FontSize',11, ...
         'FontWeight','normal');
end

sgtitle('A2A Peak Differences (within-animal deltas)');

%% D1 // A2A activity at OUTCOME Start Separated by Same-Trial Outcome - DB, DBZ

figure;
tiledlayout(2,2);
nexttile; hold on
[hOStartD1hit,metaOStartD1hit] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","outcome", "which","debleached", "outcome","hit",...
    "Color",hitColor, "FillAlpha",0.12, "weight_by","animal");
%[hOStartD1miss,metaOStartD1miss] = plotPhotometryQuery(streams, trials, signalsPath, ...
%      "cell_type","d1", "align","outcome", "which","debleached", "outcome","miss",...
%      "Color",missColor, "FillAlpha",0.12, "weight_by","animal");
[hOStartD1FA,metaOStartD1FA] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","outcome", "which","debleached", "outcome","fa",...
    "Color",FAColor, "FillAlpha",0.12, "weight_by","animal");
[hOStartD1CR,metaOStartD1CR] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","outcome", "which","debleached", "outcome","cr",...
    "Color",CRColor, "FillAlpha",0.12, "weight_by","animal");


title("D1 SPN - Outcome")
ylabel("ΔF/F");
text(0.98, 0.98, 'Hit', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', hitColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Correct Rejection', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', CRColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
% text(0.98, 0.82, 'Miss', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','right', ...
%     'VerticalAlignment','top', ...
%     'Color', missColor, ...
%     'FontSize', 10, ...
%     'FontWeight','bold');
text(0.98, 0.74, 'False Alarm', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', FAColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hOStartA2Ahit,metaOStartA2Ahit] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","outcome", "which","debleached", "outcome","hit",...
    "Color",hitColor, "FillAlpha",0.12, "weight_by","animal");
%[hOStartA2Amiss,metaOStartA2Amiss] = plotPhotometryQuery(streams, trials, signalsPath, ...
%      "cell_type","a2a", "align","outcome", "which","debleached", "outcome","miss",...
%      "Color",missColor, "FillAlpha",0.12, "weight_by","animal");
[hOStartA2AFA,metaOStartA2AFA] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","outcome", "which","debleached", "outcome","fa",...
    "Color",FAColor, "FillAlpha",0.12, "weight_by","animal");
[hOStartA2ACR,metaOStartA2ACR] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","outcome", "which","debleached", "outcome","cr",...
    "Color",CRColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Outcome")
ylabel("ΔF/F");
text(0.98, 0.98, 'Hit', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', hitColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Correct Rejection', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', CRColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
% text(0.98, 0.82, 'Miss', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','right', ...
%     'VerticalAlignment','top', ...
%     'Color', missColor, ...
%     'FontSize', 10, ...
%     'FontWeight','bold');
text(0.98, 0.74, 'False Alarm', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', FAColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hOStartD1hitZ,metaOStartD1hitZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","outcome", "which","normalized", "outcome","hit",...
    "Color",hitColor, "FillAlpha",0.12, "weight_by","animal");
%[hOStartD1missZ,metaOStartD1missZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
%      "cell_type","d1", "align","outcome", "which","normalized", "outcome","miss",...
%      "Color",missColor, "FillAlpha",0.12, "weight_by","animal");
[hOStartD1FAZ,metaOStartD1FAZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","outcome", "which","normalized", "outcome","fa",...
    "Color",FAColor, "FillAlpha",0.12, "weight_by","animal");
[hOStartD1CRZ,metaOStartD1CRZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","outcome", "which","normalized", "outcome","cr",...
    "Color",CRColor, "FillAlpha",0.12, "weight_by","animal");


title("D1 SPN - Outcome")
ylabel("Z-scored ΔF/F");
text(0.98, 0.98, 'Hit', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', hitColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Correct Rejection', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', CRColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
% text(0.98, 0.82, 'Miss', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','right', ...
%     'VerticalAlignment','top', ...
%     'Color', missColor, ...
%     'FontSize', 10, ...
%     'FontWeight','bold');
text(0.98, 0.74, 'False Alarm', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', FAColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hOStartA2AhitZ,metaOStartA2AhitZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","outcome", "which","normalized", "outcome","hit",...
    "Color",hitColor, "FillAlpha",0.12, "weight_by","animal");
%[hOStartA2AmissZ,metaOStartA2AmissZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
%      "cell_type","a2a", "align","outcome", "which","normalized", "outcome","miss",...
%      "Color",missColor, "FillAlpha",0.12, "weight_by","animal");
[hOStartA2AFAZ,metaOStartA2AFAZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","outcome", "which","normalized", "outcome","fa",...
    "Color",FAColor, "FillAlpha",0.12, "weight_by","animal");
[hOStartA2ACRZ,metaOStartA2ACRZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","outcome", "which","normalized", "outcome","cr",...
    "Color",CRColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Outcome")
ylabel("Z-scored ΔF/F");
text(0.98, 0.98, 'Hit', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', hitColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Correct Rejection', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', CRColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
% text(0.98, 0.82, 'Miss', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','right', ...
%     'VerticalAlignment','top', ...
%     'Color', missColor, ...
%     'FontSize', 10, ...
%     'FontWeight','bold');
text(0.98, 0.74, 'False Alarm', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', FAColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

%% D1 // A2A activity at TONE Start Separated by Go vs. No Go Tone - DB, DBZ

figure;
tiledlayout(2,2);
nexttile; hold on
[hToStartD1Go,metaToStartD1Go] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_type","go",...
    "Color",goColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1NoGo,metaToStartD1NoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_type","nogo",...
    "Color",nogoColor, "FillAlpha",0.12, "weight_by","animal");


title("D1 SPN - Tone Start")
ylabel("ΔF/F");
text(0.98, 0.98, 'Go Tone', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', goColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'No Go Tone', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', nogoColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hToStartA2AGo,metaToStartA2AGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_type","go",...
    "Color",goColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2ANoGo,metaToStartA2ANoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_type","nogo",...
    "Color",nogoColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Tone Start")
ylabel("ΔF/F");
text(0.98, 0.98, 'Go Tone', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', goColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'No Go Tone', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', nogoColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hToStartD1GoZ,metaToStartD1GoZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","normalized", "tone_type","go",...
    "Color",goColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1NoGoZ,metaToStartD1NoGoZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","normalized", "tone_type","nogo",...
    "Color",nogoColor, "FillAlpha",0.12, "weight_by","animal");

title("D1 SPN - Tone Start")
ylabel("Z-scored ΔF/F");
text(0.98, 0.98, 'Go Tone', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', goColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'No Go Tone', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', nogoColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hToStartA2AGoZ,metaToStartA2AGoZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","normalized", "tone_type","go",...
    "Color",goColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2ANoGoZ,metaToStartA2ANoGoZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","normalized", "tone_type","nogo",...
    "Color",nogoColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Tone Start")
ylabel("Z-scored ΔF/F");
text(0.98, 0.98, 'Go Tone', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', goColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'No Go Tone', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', nogoColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

%% D1 // A2A activity at TONE Start Separated by High vs. Low Tone - DB, DBZ

figure;
tiledlayout(2,2);
nexttile; hold on
[hToStartD1Hi,metaToStartD1Hi] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","high",...
    "Color",highToneColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1Lo,metaToStartD1Lo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","low",...
    "Color",lowToneColor, "FillAlpha",0.12, "weight_by","animal");


title("D1 SPN - Tone Start")
ylabel("ΔF/F");
text(0.98, 0.98, 'High Tones', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', highToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Low Tones', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', lowToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hToStartA2AHi,metaToStartA2AHi] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","high",...
    "Color",highToneColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2ALo,metaToStartA2ALo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","low",...
    "Color",lowToneColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Tone Start")
ylabel("ΔF/F");
text(0.98, 0.98, 'High Tones', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', highToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Low Tones', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', lowToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hToStartD1HiZ,metaToStartD1HiZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","normalized", "tone_freq","high",...
    "Color",highToneColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1NoGoZ,metaToStartD1NoGoZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","normalized", "tone_freq","low",...
    "Color",lowToneColor, "FillAlpha",0.12, "weight_by","animal");

title("D1 SPN - Tone Start")
ylabel("Z-scored ΔF/F");
text(0.98, 0.98, 'High Tones', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', highToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Low Tones', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', lowToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hToStartA2AHiZ,metaToStartA2AHiZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","normalized", "tone_freq","high",...
    "Color",highToneColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2ALoZ,metaToStartA2ALoZ] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","normalized", "tone_freq","low",...
    "Color",lowToneColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Tone Start")
ylabel("Z-scored ΔF/F");
text(0.98, 0.98, 'High Tones', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', highToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Low Tones', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', lowToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

%% D1 // A2A activity at TONE Start on Go vs. No Go Trials by High vs. Low Tone - DB
figure;
tiledlayout(2,2);
nexttile; hold on
[hToStartD1HiGo,metaToStartD1HiGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","high","tone_type","go",...
    "Color",goColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1LoNoGo,metaToStartLoNoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","low","tone_type","nogo",...
    "Color",nogoColor, "FillAlpha",0.12, "weight_by","animal");


title("D1 SPN - Tone Start; Go is High")
ylabel("ΔF/F");
text(0.98, 0.98, 'Go tone (high)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', goColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'No Go tone (low)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', nogoColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');


nexttile; hold on
[hToStartD1LoGo,metaToStartD1LoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","low","tone_type","go",...
    "Color",goColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1HiNoGo,metaToStartD1HiNoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","high","tone_type","nogo",...
    "Color",nogoColor, "FillAlpha",0.12, "weight_by","animal");


title("D1 SPN - Tone Start; Go is Low")
ylabel("ΔF/F");
text(0.98, 0.98, 'Go tone (low)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', goColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'No Go tone (high)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', nogoColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hToStartA2AHiGo,metaToStartA2AHiGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","high","tone_type","go",...
    "Color",goColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2ALoNoGo,metaToStartA2ALoNoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","low","tone_type","nogo",...
    "Color",nogoColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Tone Start; Go is High")
ylabel("ΔF/F");
text(0.98, 0.98, 'Go tone (high)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', goColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'No Go tone (low)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', nogoColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');


nexttile; hold on
[hToStartA2ALoGo,metaToStartA2ALoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","low","tone_type","go",...
    "Color",goColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2AHiNoGo,metaToStartA2AHiNoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","high","tone_type","nogo",...
    "Color",nogoColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Tone Start; Go is Low")
ylabel("ΔF/F");
text(0.98, 0.98, 'Go tone (low)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', goColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'No Go tone (high)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', nogoColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

%% D1 // A2A activity at TONE Start on High vs. Low Tone Trials Separated by Go vs. No Go - DB
figure;
tiledlayout(2,2);
nexttile; hold on
[hToStartD1HiGo,metaToStartD1HiGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","high","tone_type","go",...
    "Color",goColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1HiNoGo,metaToStartD1HiNoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","high","tone_type","nogo",...
    "Color",nogoColor, "FillAlpha",0.12, "weight_by","animal");


title("D1 SPN - Tone Start; HIGH")
ylabel("ΔF/F");
text(0.98, 0.98, 'Go tone (high)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', goColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'No Go tone (high)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', nogoColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');


nexttile; hold on
[hToStartD1LoNoGo,metaToStartD1LoNoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","low","tone_type","nogo",...
    "Color",nogoColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1LoGo,metaToStartD1LoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","low","tone_type","go",...
    "Color",goColor, "FillAlpha",0.12, "weight_by","animal");


title("D1 SPN - Tone Start; LOW")
ylabel("ΔF/F");
text(0.98, 0.98, 'No Go tone (low)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', nogoColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Go tone (low)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', goColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hToStartA2AHiGo,metaToStartA2AHiGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","high","tone_type","go",...
    "Color",goColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2AHiNoGo,metaToStartA2AHiNoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","high","tone_type","nogo",...
    "Color",nogoColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Tone Start; HIGH")
ylabel("ΔF/F");
text(0.98, 0.98, 'Go tone (high)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', goColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'No Go tone (high)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', nogoColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');


nexttile; hold on
[hToStartA2ALoGo,metaToStartA2ALoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","low","tone_type","go",...
    "Color",goColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2ALoNoGo,metaToStartA2ALoNoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","low","tone_type","nogo",...
    "Color",nogoColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Tone Start; LOW")
ylabel("ΔF/F");
text(0.98, 0.98, 'Go tone (low)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', goColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'No Go tone (low)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', nogoColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');


%% High Go vs. Low Go; High No Go vs. Low No Go - DB
figure;
tiledlayout(2,2);
nexttile; hold on
[hToStartD1HiGo,metaToStartD1HiGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","high","tone_type","go",...
    "Color",highToneColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1LoGo,metaToStartD1LoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","low","tone_type","go",...
    "Color",lowToneColor, "FillAlpha",0.12, "weight_by","animal");

title("D1 SPN - Tone Start; GO")
ylabel("ΔF/F");
text(0.98, 0.98, 'Go tone (high)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', highToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Go tone (low)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', lowToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');


nexttile; hold on
[hToStartD1HiNoGo,metaToStartD1HiNoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","high","tone_type","nogo",...
    "Color",highToneColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartD1LoNoGo,metaToStartD1LoNoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","d1", "align","tone_start", "which","debleached", "tone_freq","low","tone_type","nogo",...
    "Color",lowToneColor, "FillAlpha",0.12, "weight_by","animal");



title("D1 SPN - Tone Start; NO GO")
ylabel("ΔF/F");
text(0.98, 0.98, 'No Go tone (high)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', highToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'No Go tone (low)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', lowToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');

nexttile; hold on
[hToStartA2AHiGo,metaToStartA2AHiGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","high","tone_type","go",...
    "Color",highToneColor, "FillAlpha",0.12, "weight_by","animal");
[hToStartA2ALoGo,metaToStartA2ALoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","low","tone_type","go",...
    "Color",lowToneColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Tone Start; GO")
ylabel("ΔF/F");
text(0.98, 0.98, 'Go tone (high)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', highToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'Go tone (low)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', lowToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');


nexttile; hold on
[hToStartA2AHiNoGo,metaToStartA2AHiNoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","high","tone_type","nogo",...
    "Color",highToneColor, "FillAlpha",0.12, "weight_by","animal");

[hToStartA2ALoNoGo,metaToStartA2ALoNoGo] = plotPhotometryQuery(streams, trials, signalsPath, ...
    "cell_type","a2a", "align","tone_start", "which","debleached", "tone_freq","low","tone_type","nogo",...
    "Color",lowToneColor, "FillAlpha",0.12, "weight_by","animal");


title("A2A SPN - Tone Start; NO GO")
ylabel("ΔF/F");
text(0.98, 0.98, 'No Go tone (high)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', highToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'No Go tone (low)', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', lowToneColor, ...
    'FontSize', 10, ...
    'FontWeight','bold');


%% Single-trial traces
%D1 Hit sorted by RT
[hD1H, metaD1H, singleD1H] = plotPhotometryQuery( ...
    streams, trials, signalsPath, ...
    "cell_type", "d1", ...
    "align", "tone_start", ...
    "which", "debleached", ...
    "outcome", "hit", ...
    "tone_type", "any", ...
    "weight_by", "animal", ...          % irrelevant for single-trial but fine
    "return_single_trials", true, ...
    "sort_by", "rt", ...
    "peak_win", [0 0.25], ...
    "base_win", [-0.5 0], ...
    "max_trials_per_stream", inf ...
    );

%plot heatmap
single = singleD1H;
ok = single.rt >= 0.08 & single.rt <= 1.5;   % adjust 0.08–0.1 if you prefer
X = single.X(ok,:);
rt = single.rt(ok);
t = single.t;

stride = 10;
Xshow = X(1:stride:end,:);
rtshow = rt(1:stride:end);

lo = prctile(Xshow(:), 2);
hi = prctile(Xshow(:), 98);

figure;
imagesc(t, 1:size(Xshow,1), Xshow);
set(gca,'YDir','normal');
xline(0,'--');
caxis([lo hi]);
colorbar;
xlabel('Time from tone (s)');
ylabel(sprintf('Trials (every %dth; RT-sorted)', stride));
title('D1 Hits – downsampled single-trial heatmap');

hold on;
plot(rtshow, 1:numel(rtshow), 'k.', 'MarkerSize', 3);


%% Stream-wise statistics (mean, SD, median, SD-rob, P95, large event rate)
T = streamFullTraceStats(streams, signalsPath, "debleached");
T = T(ismember(floor(T.task_phase),[3,13]),:);
T = T((strcmp(T.side,"R") ==1| strcmp(T.side,"L") ==1),:);
T = T(~isnan(T.go_is_high),:);


d1mean = mean(T.mu(strcmp(T.cell_type,"d1") == 1));
fprintf("D1 Mean (whole session): %f",d1mean);
d1sd = mean(T.sd(strcmp(T.cell_type,"d1") == 1));
fprintf(", SD = %f, N = %f",d1sd, numel(T.mu(strcmp(T.cell_type,"d1") == 1)));
d1medx = mean(T.medx(strcmp(T.cell_type,"d1") == 1));
d1sdrob = mean(T.sdrob(strcmp(T.cell_type,"d1") == 1));
d1p95 = mean(T.p95(strcmp(T.cell_type,"d1") == 1));
d1LER = mean(T.largeEventRate(strcmp(T.cell_type,"d1") == 1));
fprintf("\nD1 Median = %f; SD-Rob = %f; p95 = %f, Large Event Rate = %f",d1medx,d1sdrob,d1p95,d1LER);
a2amean = mean(T.mu(strcmp(T.cell_type,"a2a") == 1));
fprintf("\nA2A Mean (whole session): %f",a2amean);
a2asd = mean(T.sd(strcmp(T.cell_type,"a2a") == 1));
fprintf(", SD = %f, N = %f\n",a2asd,numel(T.mu(strcmp(T.cell_type,"a2a") == 1)));
a2amedx = mean(T.medx(strcmp(T.cell_type,"a2a") == 1));
a2asdrob = mean(T.sdrob(strcmp(T.cell_type,"a2a") == 1));
a2ap95 = mean(T.p95(strcmp(T.cell_type,"a2a") == 1));
a2aLER = mean(T.largeEventRate(strcmp(T.cell_type,"a2a") == 1));
fprintf("A2A Median = %f; SD-Rob = %f; p95 = %f, Large Event Rate = %f\n",a2amedx,a2asdrob,a2ap95,a2aLER);

%
[xD1, xA2A] = collectSignalsByCellType(streams, signalsPath, "debleached");

% Same bin edges so the comparison is fair
edges = linspace(min([xD1; xA2A]), max([xD1; xA2A]), 200);

%
figure; hold on
histogram(xD1,  edges, 'Normalization','pdf', 'DisplayStyle','stairs','EdgeColor',d1Color./255,'LineWidth',2);
histogram(xA2A, edges, 'Normalization','pdf', 'DisplayStyle','stairs','EdgeColor',a2aColor./255,'LineWidth',2);
xlabel('\DeltaF/F'); ylabel('PDF'); box off
text(0.98, 0.98, 'D1-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', d1Color./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'A2A-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', a2aColor./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');
xlim([-10,20]);

figure; hold on
histogram(xD1,  edges, 'Normalization','cdf', 'DisplayStyle','stairs','EdgeColor',d1Color./255,'LineWidth',2);
histogram(xA2A, edges, 'Normalization','cdf', 'DisplayStyle','stairs','EdgeColor',a2aColor./255,'LineWidth',2);
xlabel('\DeltaF/F'); ylabel('PDF'); box off
text(0.98, 0.98, 'D1-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', d1Color./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');
text(0.98, 0.90, 'A2A-SPNs', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color', a2aColor./255, ...
    'FontSize', 10, ...
    'FontWeight','bold');
xlim([-10,20]);

%% LOCAL HELPER FUNCTIONS



function S = loadStreamByRow(h5file, row, which)
% which: "unfiltered" | "debleached" | "normalized"
switch which
    case "unfiltered", pSig = row.path_unfiltered;
    case "debleached", pSig = row.path_debleached;
    case "normalized", pSig = row.path_normalized;
    otherwise, error("Unknown which=%s", which);
end

S.signal = h5read(h5file, pSig);
S.time   = h5read(h5file, row.path_time);
end



function [X, tRel] = extractAligned(S, eventTimes, win)
fs   = 1/median(diff(S.time));
tRel = win(1):1/fs:win(2);

nT = numel(eventTimes);
nS = numel(tRel);
X  = nan(nT, nS);

for i = 1:nT
    t0 = eventTimes(i);
    if isnan(t0), continue; end
    tq = t0 + tRel;
    X(i,:) = interp1(S.time, S.signal, tq, "linear", NaN);
end
end

function tr = trialsForStream(trials, streamsRow)
tr = trials(trials.session_uid == streamsRow.session_uid & ...
    trials.animal_id   == streamsRow.animal_id, :);
end

function [h,meta,single] = plotPhotometryQuery(streams, trials, h5file, varargin)

p = inputParser;
addParameter(p, "cell_type", "any");        % "d1" | "a2a" | "any"
addParameter(p, "align", "tone_start");     % "trial_start" | "tone_start" | "outcome"
addParameter(p, "which", "debleached");     % "unfiltered" | "debleached" | "normalized"
addParameter(p, "win", [-2 2]);             % seconds
addParameter(p, "outcome", "any");          % "hit"|"miss"|"cr"|"fa"|...
addParameter(p, "tone_type", "any");        % "go"|"nogo"|"any"
addParameter(p, "task_phase", "any");       % 3 or 13 or "any"
addParameter(p, "go_is_high", "any");       % 0/1 or "any"
addParameter(p, "side", "any");             % "L"|"R"|"unused"|"any"
addParameter(p, "exclude_nrxn", true);      % default exclude
addParameter(p, "max_streams", inf);
addParameter(p, "max_trials_per_stream", inf);
addParameter(p, "plot_individual", false);  % start clean
addParameter(p, "weight_by", "trial");      % "trial" or "stream" (see note)
addParameter(p, "Color", [0 0 0]);     % RGB, 0–1 or 0–255
addParameter(p, "FillAlpha", 0.15);    % transparency for SEM band
addParameter(p, "perf_only", true);   % default: only hit/miss/cr/fa
addParameter(p, "tone_freq", "any");  % "high" | "low" | "any"
addParameter(p, "return_single_trials", false);
addParameter(p, "sort_by", "none");   % "rt" | "peak" | "baseline" | "trial_index"
addParameter(p, "peak_win", [0 0.25]);
addParameter(p, "base_win", [-0.5 0]);

parse(p, varargin{:});
o = p.Results;

S = streams;
single = struct();


% basic stream filters
S = S(S.has_signal==true, :);
if o.exclude_nrxn
    S = S(S.nrxn==0, :);
end
if o.cell_type ~= "any"
    S = S(S.cell_type == o.cell_type, :);
end
if o.task_phase ~= "any"
    S = S(S.task_phase == o.task_phase, :);
end
if o.go_is_high ~= "any"
    S = S(S.go_is_high == o.go_is_high, :);
end
if o.side ~= "any"
    S = S(S.side == o.side, :);
end



if height(S)==0
    error("No streams match the requested filters.");
end

S = S(1:min(height(S), o.max_streams), :);

% collect aligned matrices in a cell (avoid slow growing arrays)
Xc = cell(height(S),1);
streamAnimal = cell(height(S),1);
streamSide = cell(height(S),1);
tc = [];
keepStream = false(height(S),1);
inc = table();
inc.stream_uid   = strings(0,1);
inc.animal_id    = strings(0,1);
inc.session_uid  = strings(0,1);
inc.side         = strings(0,1);
inc.n_trials     = zeros(0,1);

if o.return_single_trials
    allX = zeros(0,0);          % will set after first stream determines nSamples
    allRT = []; allPeak = []; allBase = [];
    allOutcome = strings(0,1);
    allToneType = strings(0,1);
    allToneFreq = strings(0,1); % optional
    allAnimal = strings(0,1);
    allSession = strings(0,1);
    allStream = strings(0,1);
    allSide = strings(0,1);
    allGoIsHigh = [];           % numeric
end


for k = 1:height(S)
    row = S(k,:);
    sig = loadStreamByRow(h5file, row, o.which);

    % trials for this stream (join by session_uid + animal_id)
    tr = trials(trials.session_uid == row.session_uid & trials.animal_id == row.animal_id, :);

    % trial filters
    tr = tr(tr.is_valid==true, :);
    if o.exclude_nrxn && ismember("nrxn", tr.Properties.VariableNames)
        tr = tr(tr.nrxn==0, :);
    end
    % If you only want performance trials (hit/miss/cr/fa)
    if o.perf_only
        tr = tr(ismember(tr.outcome, ["hit","miss","cr","fa"]), :);
    end
    if o.outcome ~= "any"
        tr = tr(tr.outcome == o.outcome, :);
    end
    if o.tone_type ~= "any"
        tr = tr(tr.tone_type == o.tone_type, :);
    end
    % ---- NEW: filter by physical tone frequency (high/low) ----
    if o.tone_freq ~= "any"
        if ~ismember("go_is_high", tr.Properties.VariableNames)
            error("trials table is missing variable 'go_is_high' needed for tone_freq filtering.");
        end

        % derive physical frequency for each trial
        tf = strings(height(tr),1);  % "high"/"low"/""
        isGo   = tr.tone_type == "go";
        isNoGo = tr.tone_type == "nogo";

        % Go trials: go_is_high maps directly
        tf(isGo  & tr.go_is_high==1) = "high";
        tf(isGo  & tr.go_is_high==0) = "low";

        % NoGo trials: opposite mapping
        tf(isNoGo & tr.go_is_high==1) = "low";
        tf(isNoGo & tr.go_is_high==0) = "high";

        % If there are other tone_type values, they stay "" and will be dropped by the filter below.
        tr = tr(tf == o.tone_freq, :);
    end



    if height(tr)==0
        continue
    end

    % alignment times
    switch o.align
        case "trial_start", ev = tr.t_trial_start;
        case "tone_start",  ev = tr.t_tone_start;
        case "outcome",     ev = tr.t_outcome;
        otherwise, error("Unknown align=%s", o.align);
    end

    % subsample trials if requested
    if isfinite(o.max_trials_per_stream) && height(tr) > o.max_trials_per_stream
        ix = randperm(height(tr), o.max_trials_per_stream);
        ev = ev(ix);
    end

    [X, tRel] = extractAligned(sig, ev, o.win);

    % 4) define keepTrial NOW
    fracNaN   = mean(isnan(X),2);
    keepTrial = fracNaN < 0.2;
    
    % 5) apply keepTrial to BOTH X and tr
    X  = X(keepTrial,:);
    tr = tr(keepTrial,:);
    if isempty(X), continue; end
    tc = tRel;

    if o.return_single_trials

        % 1) Compute RT relative to tone (only meaningful for Go responses; others -> NaN)
        % Define RT as outcome - tone_start (since outcome==first lick for go trials)
        rt = tr.t_outcome - tr.t_tone_start;     % height(tr) x 1
        rt = rt(keepTrial);                      % align with X rows

        % 2) Peak and baseline from X in windows
        pkIx = tc >= o.peak_win(1) & tc <= o.peak_win(2);
        bsIx = tc >= o.base_win(1) & tc <= o.base_win(2);

        peakVal = max(X(:, pkIx), [], 2, "omitnan");     % nKept x 1 (or mean)
        baseVal = mean(X(:, bsIx), 2, "omitnan");        % nKept x 1

        % 3) Trial labels (aligned)
        out = string(tr.outcome);
        out = out(keepTrial);

        tt = string(tr.tone_type);
        tt = tt(keepTrial);

        gih = tr.go_is_high;
        gih = gih(keepTrial);

        % optional: derived physical tone freq (high/low)
        tf = strings(numel(tt),1);
        isGo   = tt == "go";
        isNoGo = tt == "nogo";
        tf(isGo   & gih==1) = "high";
        tf(isGo   & gih==0) = "low";
        tf(isNoGo & gih==1) = "low";
        tf(isNoGo & gih==0) = "high";

        % 4) Stream-level IDs replicated per trial
        nKept = size(X,1);
        animal = repmat(string(row.animal_id),  nKept, 1);
        sess   = repmat(string(row.session_uid), nKept, 1);
        stream = repmat(string(row.stream_uid),  nKept, 1);
        side   = repmat(string(row.side),        nKept, 1);

        % 5) Concatenate into “all*” accumulators
        if isempty(allX)
            allX = X;
        else
            allX = [allX; X];
        end
        allRT      = [allRT; rt];
        allPeak    = [allPeak; peakVal];
        allBase    = [allBase; baseVal];
        allOutcome = [allOutcome; out];
        allToneType= [allToneType; tt];
        allToneFreq= [allToneFreq; tf];
        allGoIsHigh= [allGoIsHigh; gih];
        allAnimal  = [allAnimal; animal];
        allSession = [allSession; sess];
        allStream  = [allStream; stream];
        allSide    = [allSide; side];
    end



    Xc{k} = X;
    streamAnimal{k} = row.animal_id;
    streamSide{k}   = row.side;

    keepStream(k) = true;
    nUsed = size(X,1);
    if nUsed > 0
        inc = [inc; table(row.stream_uid, row.animal_id, row.session_uid, row.side, nUsed, ...
            'VariableNames', ["stream_uid","animal_id","session_uid","side","n_trials"])];
    end
end

Xc = Xc(keepStream);
if isempty(Xc)
    error("No trials survived filtering across all matching streams.");
else
    streamAnimal = streamAnimal(keepStream);
    streamSide   = streamSide(keepStream);
end
if o.return_single_trials
    single.X = allX;
    single.t = tc;
    single.rt = allRT;
    single.peak = allPeak;
    single.base = allBase;
    single.outcome = allOutcome;
    single.tone_type = allToneType;
    single.tone_freq = allToneFreq;
    single.go_is_high = allGoIsHigh;
    single.animal_id = allAnimal;
    single.session_uid = allSession;
    single.stream_uid = allStream;
    single.side = allSide;
    single.cell_type = repmat(string(o.cell_type), size(allX,1), 1); % or leave blank if "any"
end

if o.return_single_trials && o.sort_by ~= "none"
    switch o.sort_by
        case "rt",       key = single.rt;
        case "peak",     key = single.peak;
        case "baseline", key = single.base;
        case "trial_index", key = (1:size(single.X,1))';
        otherwise, key = [];
    end

    if ~isempty(key)
        [~,ord] = sort(key, "ascend", "MissingPlacement","last");
        f = fieldnames(single);
        for i = 1:numel(f)
            v = single.(f{i});
            if isvector(v) && numel(v) == size(single.X,1)
                single.(f{i}) = v(ord,:);
            end
        end
        single.X = single.X(ord,:);
    end
end








switch o.weight_by

    case "trial"
        % all trials pooled
        allX = vertcat(Xc{:});
        m = mean(allX, 1, "omitnan");
        s = std(allX, 0, 1, "omitnan") ./ sqrt(sum(~isnan(allX),1));
        nLabel = size(allX,1) + " trials";

    case "stream"
        % one trace per stream
        streamMeans = cellfun(@(x) mean(x,1,"omitnan"), Xc, "UniformOutput", false);
        M = vertcat(streamMeans{:}); % nStreams x nSamples
        m = mean(M, 1, "omitnan");
        s = std(M, 0, 1, "omitnan") ./ sqrt(size(M,1));
        nLabel = size(M,1) + " streams";

    case "animal"
        % ----- NEW: hierarchical animal averaging -----

        % 1) mean within each stream
        streamMeans = cellfun(@(x) mean(x,1,"omitnan"), Xc, "UniformOutput", false);
        Mstream = vertcat(streamMeans{:}); % nStreams x nSamples
        
        % --- NEW: store stream-level outputs for stats ---
        meta.stream_traces = Mstream;
        meta.stream_uid    = string(inc.stream_uid);   % one row per stream
        meta.animal_id     = string(inc.animal_id);
        meta.session_uid   = string(inc.session_uid);
        meta.side          = string(inc.side);

        % (optional sanity)
        assert(size(Mstream,1) == numel(meta.stream_uid), 'Mstream rows must match inc rows.');

        animalVec = string(streamAnimal);   % convert cell -> string
        % 2) group streams by animal
        [Ga, animalList] = findgroups(animalVec);

        % 3) mean across streams within each animal
        Manimal = splitapply(@(rows) mean(rows,1,"omitnan"), Mstream, Ga);

        % 4) mean + SEM across animals
        m = mean(Manimal, 1, "omitnan");
        s = std(Manimal, 0, 1, "omitnan") ./ sqrt(size(Manimal,1));
        nLabel = size(Manimal,1) + " animals";

    otherwise
        error("Unknown weight_by=%s", o.weight_by);
end

meta.included = inc;
meta.n_streams = height(unique(inc(:, "stream_uid")));
meta.n_animals = numel(unique(inc.animal_id));
meta.n_sessions = numel(unique(inc.session_uid));
meta.n_trials = sum(inc.n_trials);
meta.animal_list  = animalList;
meta.n_animals    = numel(animalList);
meta.animal_traces = Manimal;  % useful for stats later



% plot
% if nargout == 0
%     figure; hold on;
% end

h = plotMeanSEM(tc, m, s, o.Color, ...
    "FillAlpha", o.FillAlpha);

xline(0, "--");
xlabel("Time (s)");
ylabel(o.which);

title(sprintf("cell=%s align=%s outcome=%s tone=%s phase=%s (%s)", ...
    o.cell_type, o.align, o.outcome, o.tone_type, ...
    string(o.task_phase), nLabel));
end

function h = plotMeanSEM(t, m, sem, rgb, varargin)
% h = plotMeanSEM(t, m, sem, rgb, "FillAlpha",0.15, "LineWidth",2)

p = inputParser;
addParameter(p, "FillAlpha", 0.15);
addParameter(p, "LineWidth", 1);
parse(p, varargin{:});
o = p.Results;

rgb = double(rgb(:)');
if any(rgb > 1), rgb = rgb/255; end

% Shaded SEM band
x = [t(:); flipud(t(:))]';
y = [(m(:)-sem(:)); flipud(m(:)+sem(:))]';
h.band = fill(x, y, rgb, ...
    "FaceAlpha", o.FillAlpha, ...
    "EdgeColor", "none");

% Mean line
h.line = plot(t, m, ...
    "Color", rgb, ...
    "LineWidth", o.LineWidth);
end


function T = streamFullTraceStats(streams, h5file, which)
if nargin < 3, which = "debleached"; end

T = streams(:, ["stream_uid","animal_id","session_uid","cell_type","task_phase","side","go_is_high"]);
T.mu = nan(height(T),1);
T.sd = nan(height(T),1);
T.n  = zeros(height(T),1);
T.medx = nan(height(T),1);
T.sdrob = nan(height(T),1);
T.p95 = nan(height(T),1);
T.largeEventRate = nan(height(T),1);

for k = 1:height(T)
    row = streams(k,:);
    S = loadStreamByRow(h5file, row, which);
    x = S.signal;
    mu = mean(x, "omitnan");
    T.mu(k) = mu;
    sd = std(x, 0, "omitnan");
    T.sd(k) = sd;
    T.n(k)  = sum(~isnan(x));
    medx = median(x,"omitnan");
    T.medx(k) = medx;
    xnn = x(~isnan(x));
    if isempty(xnn)
        sdrob = NaN;
    else
        medx_local = median(xnn);
        sdrob = 1.4826 * median(abs(xnn - medx_local));
    end

    T.sdrob(k) = sdrob;
    p95 = prctile(x(~isnan(x)),95);
    T.p95(k) = p95;
    const = 4;
    T.largeEventConst(k) = const;
    T.largeEventRate(k) = mean(x > medx + const*sdrob,'omitnan');
end
end




function [xD1, xA2A] = collectSignalsByCellType(streams, h5file, which)
if nargin < 3, which = "debleached"; end

isD1  = streams.cell_type == "d1";
isA2A = streams.cell_type == "a2a";   % adjust if your labels differ

xD1  = [];
xA2A = [];

for k = 1:height(streams)
    S = loadStreamByRow(h5file, streams(k,:), which);
    x = S.signal;
    x = x(~isnan(x));
    if isempty(x), continue; end

    if isD1(k)
        xD1 = [xD1; x(:)];
    elseif isA2A(k)
        xA2A = [xA2A; x(:)];
    end
end
end

function auc2 = auc2bins_stream(t, Mstream, t0, tMid, tEnd)
% t: 1 x nTime (or nTime x 1)
% Mstream: nStreams x nTime
% auc2: nStreams x 2  (early, late)

t = t(:)';  % row
ixE = t>=t0   & t<tMid;
ixL = t>=tMid & t<=tEnd;

aucE = trapz(t(ixE), Mstream(:,ixE), 2);
aucL = trapz(t(ixL), Mstream(:,ixL), 2);

auc2 = [aucE, aucL];
end


function h = plot_peak_triplet_by_animal(Tpk, titleStr)
% Tpk must have vars: outcome, animal_id, session_uid, stream_uid, peak
% outcome values expected: 'hit','fa','cr' (case-insensitive ok)

% --- sanitize outcomes
out = lower(string(Tpk.outcome));
Tpk.outcome = categorical(out);

% Keep only the three outcomes we care about
keep = ismember(Tpk.outcome, categorical(["hit","fa","cr"]));
T = Tpk(keep,:);

% --- 1) collapse streams within a session (animal × session × outcome)
G1 = findgroups(T.animal_id, T.session_uid, T.outcome);
peak_sess = splitapply(@mean, T.peak, G1);

animal_sess = splitapply(@(x)x(1), string(T.animal_id), G1);
sess_uid    = splitapply(@(x)x(1), string(T.session_uid), G1);
outcome     = splitapply(@(x)x(1), T.outcome, G1);

Tsess = table(animal_sess, sess_uid, outcome, peak_sess, ...
    'VariableNames', {'animal_id','session_uid','outcome','peak'});

% --- 2) collapse sessions within animal (animal × outcome) -> one dot per animal per condition
G2 = findgroups(Tsess.animal_id, Tsess.outcome);
peak_animal = splitapply(@mean, Tsess.peak, G2);

animal_id = splitapply(@(x)x(1), Tsess.animal_id, G2);
outcome2  = splitapply(@(x)x(1), Tsess.outcome, G2);

Tanimal = table(string(animal_id), outcome2, peak_animal, ...
    'VariableNames', {'animal_id','outcome','peak'});

% --- pivot to wide: one row per animal, columns hit/fa/cr
animals = unique(Tanimal.animal_id);
Y = nan(numel(animals),3); % [hit fa cr]

for i = 1:numel(animals)
    a = animals(i);
    for j = 1:3
        lab = ["hit","fa","cr"];
        idx = (Tanimal.animal_id==a) & (Tanimal.outcome==categorical(lab(j)));
        if any(idx)
            Y(i,j) = Tanimal.peak(find(idx,1,'first'));
        end
    end
end

% optionally drop animals missing any condition
valid = all(isfinite(Y),2);
Y = Y(valid,:);
animals = animals(valid);

% --- compute group mean and SEM
mu  = mean(Y,1,'omitnan');
sem = std(Y,0,1,'omitnan') ./ sqrt(sum(isfinite(Y),1));

% --- plot
x = 1:3; % hit, fa, cr

h = figure('Color','w'); hold on;

% thin lines per animal
for i = 1:size(Y,1)
    plot(x, Y(i,:), '-', 'Color', [0.7 0.7 0.7], 'LineWidth', 0.75);
end

% animal points
for j = 1:3
    scatter(ones(size(Y,1),1)*x(j), Y(:,j), 28, ...
        'MarkerFaceColor',[0.5 0.5 0.5], 'MarkerEdgeColor','none', ...
        'MarkerFaceAlpha', 0.75);
end

% group mean ± SEM (big black)
errorbar(x, mu, sem, 'k', 'LineWidth', 2, 'CapSize', 10);
scatter(x, mu, 80, 'k', 'filled');

% cosmetics
set(gca,'XLim',[0.5 3.5], 'XTick', x, 'XTickLabel', {'Hit','FA','CR'});
ylabel('Peak (a.u.)');
title(sprintf('%s (n=%d animals)', titleStr, size(Y,1)));
box off; set(gca,'LineWidth',1.2);

% optional: add a zero line
yline(0,'--','Color',[0.6 0.6 0.6]);

end